### ISSUE TITLE
Apple M1 Support, issues.

### ISSUE THREAD

**Issue by blue928** [PacktPublishing/Drupal-9-Module-Development-Third-Edition#1]
Hello, I'm following along in the book and developing on an M1 Macbook Pro.

Looks like these builds are suffering from the M1 issues associated with the Wodby images. It's a known issue:

https://github.com/wodby/docker4drupal/issues/465

Looks like these issues with the affected images were fixed Feb / March of this year, but the D9MDTE repo was last updated 13 months ago, before the updates were applied.

I was able to move forward by manually updating the docker-compose file, but just wanted to give you a heads up incase you wanted to update for other users on M1.

**Comment by upchuk** [comment]
@blue928 Yes, thanks, indeed, on M1 you need to use different images. Check the wodby images that work with ARM and that should be fine. You can use a docker-compose.override.yml which is meant for this kind of thing.
