### ISSUE TITLE
HelloWorldRedirectSubscriber.php > GetResponseEvent is deprecated

### ISSUE THREAD

**Issue by joshahubbers** [PacktPublishing/Drupal-9-Module-Development-Third-Edition#5]
Maybe this should be replaced with RequestEvent?
(in the use statement and line 59/62)

`public function onRequest(RequestEvent $event)`

**Comment by joshahubbers** [comment]
https://github.com/PacktPublishing/Drupal-9-Module-Development-Third-Edition/pull/6

**Comment by upchuk** [comment]
Hey there, please see my comment on the PR.
